export const ERROR_CODES = {
  INVALID_EMAIL: 'INVALID_EMAIL',
  EMAIL_TOO_LONG: 'EMAIL_TOO_LONG',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_LOCALE: 'INVALID_LOCALE',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  STRING_TOO_LONG: 'STRING_TOO_LONG',
  STRING_LENGTH_INVALID: 'STRING_LENGTH_INVALID',
  NUMBER_OUT_OF_RANGE: 'NUMBER_OUT_OF_RANGE',
  INVALID_INTEGER: 'INVALID_INTEGER',
  MUST_BE_POSITIVE: 'MUST_BE_POSITIVE',
  MUST_BE_NON_NEGATIVE: 'MUST_BE_NON_NEGATIVE',
  HTML_TOO_LONG: 'HTML_TOO_LONG',
  UNSAFE_HTML_DETECTED: 'UNSAFE_HTML_DETECTED',
  SCRIPT_TAG_DETECTED: 'SCRIPT_TAG_DETECTED',
  MIME_NOT_ALLOWED: 'MIME_NOT_ALLOWED',
  INVALID_URI: 'INVALID_URI',
  FILENAME_INVALID: 'FILENAME_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  AUDIO_DURATION_INVALID: 'AUDIO_DURATION_INVALID',
  INVALID_SORT_ORDER: 'INVALID_SORT_ORDER',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_NEEDS_UPPERCASE: 'PASSWORD_NEEDS_UPPERCASE',
  PASSWORD_NEEDS_LOWERCASE: 'PASSWORD_NEEDS_LOWERCASE',
  PASSWORD_NEEDS_NUMBER: 'PASSWORD_NEEDS_NUMBER',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  DISPLAY_NAME_INVALID: 'DISPLAY_NAME_INVALID',
  DISPLAY_NAME_TOO_SHORT: 'DISPLAY_NAME_TOO_SHORT',
  MUST_ACCEPT_TERMS: 'MUST_ACCEPT_TERMS',
  OTP_INVALID_LENGTH: 'OTP_INVALID_LENGTH',
  OTP_MUST_BE_NUMERIC: 'OTP_MUST_BE_NUMERIC',
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
  CURRENT_PASSWORD_REQUIRED: 'CURRENT_PASSWORD_REQUIRED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  BIO_TOO_LONG: 'BIO_TOO_LONG',
  SPEAK_RATE_OUT_OF_RANGE: 'SPEAK_RATE_OUT_OF_RANGE',
  INVALID_THEME: 'INVALID_THEME',
  CONFIRMATION_INVALID: 'CONFIRMATION_INVALID',
  LEVEL_OUT_OF_RANGE: 'LEVEL_OUT_OF_RANGE',
  QUALITY_OUT_OF_RANGE: 'QUALITY_OUT_OF_RANGE',
  TIME_TAKEN_INVALID: 'TIME_TAKEN_INVALID',
  SCORE_OUT_OF_RANGE: 'SCORE_OUT_OF_RANGE',
  TIME_SPENT_INVALID: 'TIME_SPENT_INVALID',
  MISTAKES_INVALID: 'MISTAKES_INVALID',
  ANSWER_TOO_LONG: 'ANSWER_TOO_LONG',
  NO_ANSWERS_PROVIDED: 'NO_ANSWERS_PROVIDED',
  WORD_REQUIRED: 'WORD_REQUIRED',
  WORD_TOO_LONG: 'WORD_TOO_LONG',
  TRANSLATION_REQUIRED: 'TRANSLATION_REQUIRED',
  TRANSLATION_TOO_LONG: 'TRANSLATION_TOO_LONG',
  NOTES_TOO_LONG: 'NOTES_TOO_LONG',
  PAGE_INVALID: 'PAGE_INVALID',
  LIMIT_OUT_OF_RANGE: 'LIMIT_OUT_OF_RANGE',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  MESSAGE_LENGTH_INVALID: 'MESSAGE_LENGTH_INVALID',
  INVALID_TYPE: 'INVALID_TYPE',
  DESCRIPTION_LENGTH_INVALID: 'DESCRIPTION_LENGTH_INVALID',
  INVALID_LESSON_ID: 'INVALID_LESSON_ID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SEC_INPUT_VALIDATION_FAIL: 'SEC_INPUT_VALIDATION_FAIL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ValidationError {
  code: ErrorCode;
  message: string;
  field?: string;
  details?: { path: string; code: string }[];
}

export function createValidationError(
  code: ErrorCode,
  message: string,
  field?: string,
  details?: { path: string; code: string }[]
): ValidationError {
  return { code, message, field, details };
}
